---
#CLACore plugin for PocketMine-MP and forks
#@Author: CLADevs Team

#-----------JOIN----------#
Always-Spawn: true
Title-Join: true
Allow-Guardian: true

#-----------RESPAWN----------#
Title-Respawn: true

#-----------ECONOMY----------#
Allow-Economy: true
Economy-Prefix: [CLADevs]

#-----------HUNGER----------#
Disable-HungerChange: true

#-----------Rank----------#
Allow-Rank: true

#-----------PING----------#
Enable-HighPingKick: true
Max-Ping: 500

#-----------NO VOID----------#
Allow-NoVoid: true
No-Void-World: world

#-----------DEVICE----------#
#Device List:
#Android = 1, IOS = 2, Windows = 7
#Allowed-Devices:
#- 1
#- 2
#- 7
...
