---
#CLACore plugin for PocketMine-MP

#@Author: CLADevs Team


#----------------------------------------# JOIN #----------------------------------------#
#Teleport you to spawn when you join & login
#true or false
Alway-Spawn: true

#----------------------------------------# RANK #----------------------------------------#
#Allow Rank in their chat and above head
#true or false
Allow-Rank: true
...